const LS_KEY="ds_ordenes";const LOGO_KEY="ds_logo";const POL_KEY="ds_policies";
let ordenes=JSON.parse(localStorage.getItem(LS_KEY)||"[]");let editIndex=null;
function loadLogo(){document.getElementById("logoImg").src=localStorage.getItem(LOGO_KEY)||"logo.png";}
loadLogo();
document.getElementById("logoInput").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{localStorage.setItem(LOGO_KEY,r.result);loadLogo();alert("Logo actualizado");};r.readAsDataURL(f);});
document.getElementById("resetLogo").addEventListener("click",()=>{if(confirm("¿Restaurar logo por defecto?")){localStorage.removeItem(LOGO_KEY);loadLogo();}});
const polArea=document.getElementById("polTxt");polArea.value=localStorage.getItem(POL_KEY)||"";
document.getElementById("savePol").addEventListener("click",()=>{localStorage.setItem(POL_KEY,polArea.value.trim());alert("Políticas guardadas");});
document.getElementById("openSettings").addEventListener("click",()=>{const p=document.getElementById("settings");p.style.right=p.style.right==="0px"?"-340px":"0";});
const historialBody=document.querySelector("#historial tbody");const form=document.getElementById("orderForm");const cancelarBtn=document.getElementById("cancelarEdicion");
function generarFolio(){const d=new Date(),y=d.getFullYear(),m=("0"+(d.getMonth()+1)).slice(-2);const c=("00"+(ordenes.filter(o=>o.folio.startsWith(`DS-${y}-${m}`)).length+1)).slice(-3);return `DS-${y}-${m}-${c}`;}
function renderHistorial(){historialBody.innerHTML="";ordenes.sort((a,b)=>new Date(b.fecha)-new Date(a.fecha));ordenes.forEach((o,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${o.folio}</td><td>${o.cliente}</td><td>${new Date(o.fecha).toLocaleString()}</td><td><button onclick="editar(${i})">Editar</button><button onclick="imprimir(${i})">Imprimir</button><button onclick="eliminar(${i})" style="color:#B00;">Eliminar</button></td>`;historialBody.appendChild(tr);});}
function resetForm(){form.reset();document.getElementById("folio").value=generarFolio();editIndex=null;cancelarBtn.style.display="none";}
resetForm();renderHistorial();
form.addEventListener("submit",e=>{e.preventDefault();const d={folio:document.getElementById("folio").value,cliente:document.getElementById("cliente").value,telefono:document.getElementById("telefono").value,modelo:document.getElementById("modelo").value,serie:document.getElementById("serie").value,accesorios:document.getElementById("accesorios").value,problema:document.getElementById("problema").value,observaciones:document.getElementById("observaciones").value,firma:document.getElementById("firma").value,fecha:new Date().toISOString(),fotos:[]};const files=document.getElementById("fotos").files;if(files.length){let l=0;[...files].forEach(f=>{const r=new FileReader();r.onload=()=>{d.fotos.push(r.result);l++;if(l===files.length)save(d);};r.readAsDataURL(f);});}else save(d);});
function save(d){if(editIndex!==null)ordenes[editIndex]=d;else ordenes.push(d);localStorage.setItem(LS_KEY,JSON.stringify(ordenes));renderHistorial();resetForm();}
function editar(i){const o=ordenes[i];editIndex=i;["folio","cliente","telefono","modelo","serie","accesorios","problema","observaciones","firma"].forEach(id=>{document.getElementById(id).value=o[id]||"";});cancelarBtn.style.display="inline-block";}
cancelarBtn.addEventListener("click",()=>resetForm());
function eliminar(i){if(confirm("¿Eliminar orden?")){ordenes.splice(i,1);localStorage.setItem(LS_KEY,JSON.stringify(ordenes));renderHistorial();}}
function imprimir(i){const o=ordenes[i],logo=document.getElementById("logoImg").src,pol=localStorage.getItem(POL_KEY)||"(Sin políticas)";const fotos=o.fotos.map(s=>`<img src='${s}' style='max-width:90px;max-height:90px;margin:2px;'>`).join("");const w=window.open("");w.document.write(`<!DOCTYPE html><html><head><meta charset='utf-8'><title>${o.folio}</title><style>body{font-family:Arial;padding:0.8cm;font-size:11px;}table{width:100%;border-collapse:collapse;}td{border:1px solid #000;padding:4px;}hr{margin:12px 0;}.pol{font-size:9pt;column-count:2;column-gap:18px;}</style></head><body><h1><img src='${logo}' style='height:60px;'> Dark System – Orden de Servicio</h1><h2>${o.folio}</h2><table><tr><td><b>Cliente:</b> ${o.cliente}<br><b>Tel:</b> ${o.telefono}</td><td><b>Fecha:</b> ${new Date(o.fecha).toLocaleString()}</td></tr><tr><td colspan='2'><b>Equipo:</b> ${o.modelo} / ${o.serie}<br><b>Accesorios:</b> ${o.accesorios}</td></tr><tr><td colspan='2'><b>Problema reportado:</b><br>${o.problema}</td></tr><tr><td colspan='2'><b>Observaciones:</b><br>${o.observaciones}</td></tr><tr><td><b>Firma cliente:</b> ${o.firma}</td><td>${fotos}</td></tr><tr><td colspan='2' style='height:26px;'><b>Nombre del cliente (letra de molde):</b> _______________________________________________</td></tr></table><hr><div class='pol'>${pol}</div></body></html>`);w.document.close();w.print();}
